.define pDMATrigger        $420B
.define pHDMATrigger       $420C

.define pDMA0Config        $4300
.define pDMA0Dest          $4301
.define pDMA0SourceOffsetW $4302
.define pDMA0SourceBank    $4304
.define pDMA0ByteCountW    $4305

.define pDMA1Config        $4310
.define pDMA1Dest          $4311
.define pDMA1SourceOffsetW $4312
.define pDMA1SourceBank    $4314
.define pDMA1ByteCountW    $4315

.define pDMA2Config        $4320
.define pDMA2Dest          $4321
.define pDMA2SourceOffsetW $4322
.define pDMA2SourceBank    $4324
.define pDMA2ByteCountW    $4325

.define pDMA3Config        $4330
.define pDMA3Dest          $4331
.define pDMA3SourceOffsetW $4332
.define pDMA3SourceBank    $4334
.define pDMA3ByteCountW    $4335

.define pDMA4Config        $4340
.define pDMA4Dest          $4341
.define pDMA4SourceOffsetW $4342
.define pDMA4SourceBank    $4344
.define pDMA4ByteCountW    $4345

.define pDMA5Config        $4350
.define pDMA5Dest          $4351
.define pDMA5SourceOffsetW $4352
.define pDMA5SourceBank    $4354
.define pDMA5ByteCountW    $4355

.define pDMA6Config        $4360
.define pDMA6Dest          $4361
.define pDMA6SourceOffsetW $4362
.define pDMA6SourceBank    $4364
.define pDMA6ByteCountW    $4365

.define pDMA7Config        $4370
.define pDMA7Dest          $4371
.define pDMA7SourceOffsetW $4372
.define pDMA7SourceBank    $4374
.define pDMA7ByteCountW    $4375
